import React, { useState } from "react";
import { Button } from "@/components/ui/Button";
import { Sparkles } from "lucide-react";
import RecommendationCard from "@/components/recommendations/RecommendationCard";
import mockRecommendations from "@/data/recommendationsData";

export default function AiRecommendations({
  onCreateTicket,
  onAcknowledge,
  onDismiss,
}) {
  const [recommendations, setRecommendations] = useState(mockRecommendations);
  const [filter, setFilter] = useState("all");

  const filteredRecommendations = recommendations.filter((rec) => {
    if (filter === "all") return true;
    if (filter === "new") return rec.status === "new";
    return rec.severity === filter;
  });

  const handleCreateTicket = (rec) => {
    setRecommendations((prev) =>
      prev.map((r) =>
        r.id === rec.id ? { ...r, status: "ticket-created" } : r
      )
    );
    onCreateTicket?.(rec);
  };

  const handleAcknowledge = (id) => {
    setRecommendations((prev) =>
      prev.map((r) => (r.id === id ? { ...r, status: "acknowledged" } : r))
    );
    onAcknowledge?.(id);
  };

  const handleDismiss = (id) => {
    setRecommendations((prev) =>
      prev.map((r) => (r.id === id ? { ...r, status: "dismissed" } : r))
    );
    onDismiss?.(id);
  };

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Sparkles className="w-5 h-5 text-emerald-500" />
            <h1 className="text-blue-600 dark:text-emerald-400 mb-1 sm:mb-2">
              AI Recommendations
            </h1>
          </div>
          <p className="text-slate-600 dark:text-slate-400 text-sm">
            Predictive insights generated by agentic AI models
          </p>
        </div>

        {/* Filters */}
        <div className="flex flex-wrap gap-2">
          <Button
            size="sm"
            onClick={() => setFilter("all")}
            className={
              filter === "all"
                ? "bg-blue-600 dark:bg-emerald-600 dark:hover:bg-emerald-600 text-white"
                : "border-slate-300 dark:bg-transparent dark:border dark:border-slate-800 dark:hover:bg-emerald-600"
            }
          >
            All ({recommendations.length})
          </Button>

          <Button
            size="sm"
            onClick={() => setFilter("new")}
            className={
              filter === "new"
                ? "dark:bg-emerald-600 dark:hover:bg-emerald-600 text-white"
                : "dark:bg-transparent border-slate-300 dark:border dark:border-slate-700 dark:hover:bg-emerald-600"
            }
          >
            New ({recommendations.filter((r) => r.status === "new").length})
          </Button>

          <Button
            size="sm"
            onClick={() => setFilter("critical")}
            className={
              filter === "critical"
                ? "bg-red-500 hover:bg-red-600 dark:bg-emerald-600 dark:hover:bg-emerald-600 text-white"
                : "border-slate-300 dark:bg-transparent dark:border dark:border-slate-700 dark:hover:bg-emerald-600"
            }
          >
            Critical (
            {recommendations.filter((r) => r.severity === "critical").length})
          </Button>
        </div>
      </div>

      {/* List */}
      <div className="space-y-4">
        {filteredRecommendations.map((rec) => (
          <RecommendationCard
            key={rec.id}
            rec={rec}
            onCreateTicket={handleCreateTicket}
            onAcknowledge={handleAcknowledge}
            onDismiss={handleDismiss}
          />
        ))}
      </div>
    </div>
  );
}
