import React, { useState, useEffect } from "react";
import { Button } from "@/components/ui/Button";
import { Sparkles, Loader2 } from "lucide-react";
import RecommendationCard from "@/components/recommendations/RecommendationCard";
import { getRecommendations } from "@/api/recommendationService";

export default function AiRecommendations({
  onCreateTicket,
  onAcknowledge,
  onDismiss,
}) {
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [filter, setFilter] = useState("all");

  useEffect(() => {
    fetchRecommendations();
  }, []);

  const fetchRecommendations = async () => {
    try {
      setLoading(true);
      const data = await getRecommendations();
      setRecommendations(data);
      setError(null);
    } catch (err) {
      console.error("Failed to fetch recommendations:", err);
      setError("Failed to load recommendations. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const filteredRecommendations = recommendations.filter((rec) => {
    if (filter === "all") return true;
    if (filter === "new") {
      // "New" means created within the last 24 hours
      const oneDayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);
      return rec.createdAt >= oneDayAgo;
    }
    return true;
  });

  const handleCreateTicket = (rec) => {
    setRecommendations((prev) =>
      prev.map((r) =>
        r.id === rec.id ? { ...r, status: "ticket-created" } : r
      )
    );
    onCreateTicket?.(rec);
  };

  const handleAcknowledge = (id) => {
    setRecommendations((prev) =>
      prev.map((r) => (r.id === id ? { ...r, status: "acknowledged" } : r))
    );
    onAcknowledge?.(id);
  };

  const handleDismiss = (id) => {
    setRecommendations((prev) =>
      prev.map((r) => (r.id === id ? { ...r, status: "dismissed" } : r))
    );
    onDismiss?.(id);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full min-h-[400px]">
        <Loader2 className="w-8 h-8 animate-spin text-emerald-500" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center h-full min-h-[400px] text-slate-500">
        <p className="mb-4">{error}</p>
        <Button onClick={fetchRecommendations}>Retry</Button>
      </div>
    );
  }

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-xl sm:text-2xl font-semibold text-blue-600 dark:text-emerald-400 mb-1 sm:mb-2">
            AI Recommendations
          </h1>
          <p className="text-slate-600 dark:text-slate-400 text-sm">
            Predictive insights generated by agentic AI models
          </p>
        </div>

        {/* Filters */}
        <div className="flex flex-wrap gap-2">
          <Button
            size="sm"
            onClick={() => setFilter("all")}
            className={
              filter === "all"
                ? "bg-blue-600 dark:bg-emerald-600 dark:hover:bg-emerald-600 text-white"
                : "border-slate-300 dark:bg-transparent dark:border dark:border-slate-800 dark:hover:bg-emerald-600"
            }
          >
            All ({recommendations.length})
          </Button>

          <Button
            size="sm"
            onClick={() => setFilter("new")}
            className={
              filter === "new"
                ? "bg-blue-600 dark:bg-emerald-600 dark:hover:bg-emerald-600 text-white"
                : "dark:bg-transparent border-slate-300 dark:border dark:border-slate-700 dark:hover:bg-emerald-600"
            }
          >
            New (
            {
              recommendations.filter(
                (r) => r.createdAt >= new Date(Date.now() - 24 * 60 * 60 * 1000)
              ).length
            }
            )
          </Button>
        </div>
      </div>

      {/* List */}
      <div className="space-y-4">
        {filteredRecommendations.map((rec) => (
          <RecommendationCard
            key={rec.id}
            rec={rec}
            onCreateTicket={handleCreateTicket}
            onAcknowledge={handleAcknowledge}
            onDismiss={handleDismiss}
          />
        ))}
      </div>
    </div>
  );
}
